### PR TITLE
[#26] Implement basic layout and landing page

### PR DESCRIPTION
**Pull request by elbenfreund**
This PR modifies our base template to match the intended layout provided by @Lokke . Furthermore it includes a static landing page that can be extended at some later stage.

Things to do before this can be merged:
- [x] Remove legacy ``landingpage`` app
- [x] Clean up ``static``. There seems to be an abundance of legacy files added.
- [x] Check if ``main.css`` is copy and pasted from somewhere and make sure all licensing requirements are met if so.
- [x] [Status button is a broken link](https://github.com/Dezentrale-eV/dezentrale_web/blob/feature/%2326_2/dezentrale_web/templates/base.html#L19)
- [x] ['start' menu entry](https://github.com/Dezentrale-eV/dezentrale_web/blob/feature/%2326_2/dezentrale_web/templates/base.html#L25) should probably point to ``dezentrale.space`` instead of ``index.html``.
- [x] Make sure the html meets our quality standards.
- [x] Although no longer mandatory, I personally feel we should give [attribution to font awesome](http://fontawesome.io/license/)
- [ ] Clean up commit history

As a sidenote:
- Please pay attention to indentation. It feels a bit shitty spending my time fixing what feels like dumped copy/paste html.
- For a first overview over djangos powerfull static file handling you probably want to have a look at [the docs](https://github.com/Dezentrale-eV/dezentrale_web/blob/feature/%2326_2/dezentrale_web/templates/base.html#L25)

Closes: #26

### CODE REVIEW

**Comment by bocian67** [comment]
Isn't the Attribution of FontAwesome in the Fontawesome css in the css file?

**Comment by elbenfreund** [comment]
Yes, but *personally* I would like to see credits to all FLOSS components either on the footer or in some deducated page/section. Something along the lines of "Created with: ...... ", "Running thanks to..." or "Powered by....". you get the idea.

**Comment by bocian67** [comment]
Maybe in the Impressum page?

**Comment by bocian67** [comment]
I talked with lokke, he told me all licenses should be in main.css which are necessary (In the first 10 lines) - so I checked the related box.

**Comment by elbenfreund** [comment]
If it is convenient for you, you can/should rebase this branch on develop to get travis integration.
Let me know if you need help with that.

**Comment by bocian67** [comment]
Could somebody with more experience rebase it so all works?

**Comment by elbenfreund** [comment]
I did the rebase. you will need to discard you local (now out for sync) branch (probably make a backup first) before you pull the rebased branch from github.

Pls let me know if everything is ok :)

**Comment by elbenfreund** [comment]
Any news on this one?

**Comment by bocian67** [comment]
I changed the href tag in base.html - if thats ok I would approve this PR, if not, I would change it back and approve it.

**Comment by bocian67** [comment]
I cannot make travis ci working properly. @elbenfreund do you get the errors? I already changed the problems of flake8, which was pep257 error, but I simply whitelisted it. I don't get the error of isort, since the command which runs it is valid and exits with no error.

**Comment by elbenfreund** [comment]
Hello @bocian67 
Those tests are there to make sure that a basic level of code quality is maintained.
- ``flake8`` checks complience with [PEP8](https://www.python.org/dev/peps/pep-0008/)
- ``isort`` makes sure that imports are sorted properly
- ``manifest`` makes sure that the package content relates to the repo content
For more details please refer to the relevant documentation.
Of cause one can whitelist entire error classes (as you did with ``E501``) or individual lines with ``  #NOQA``
**but** this is can allways be just a last resort after careful deliberation after a clear decision is made. It can not be the default reaction to failing tests as the path of least resistence. There is a reason why the test fails: the code is broken!

Please rervert ``5e8f0539094f7826edcc586d09d6373a6f6b7c4d`` and fix the issue instead. The output is quite clear about the problem. You can (and should) run the test locally using the ``test-all`` target.

With regards to the isort errors you can run ``make isort`` (which will run isort to try to sort the imports for you) to fix those errors automaticly.

I hope that points you in the right direction, if not, just get back to me.

**Comment by elbenfreund** [comment]
Guys.... really. This PR has been left untouched for weeks, and now you merge it within hours... without further feedback or considerations.
Also I thought we agreed that for the time beeing I do the merges to make sure things are as intended?
**63** commits.... **63**! I even bothered to write a checklist of things to do...
This is really messing with our git history ... please revert/rebase and fix this branch before thinking about merging this atrocity.

**Comment by bocian67** [comment]
That is in my opinion not true. Yes, this PR was open a long time - too long. But all the points were done, you made a rebase and we modified it, so Travis can work and that wagtail can work due an error, there were not many commits, but we finished it finally! We are not as accurate as your guideline would recommend, but we try to handle it your way, so I really can understand your mood right now, but we tried to fix it with the best we could do.                                                                                                                                                                                                                                                                                                                 Von: notifications@github.comGesendet: 8. Dezember 2017 1:43 vorm.An: dezentrale_web@noreply.github.comAntworten: reply@reply.github.comCc: wladi.schneider13@googlemail.com; mention@noreply.github.comBetreff: Re: [Dezentrale-eV/dezentrale_web] [#26] Implement basic layout and landing page (#69)  Guys.... really. This PR has been left untouched for weeks, and now you merge it within hours... without further feedback or considerations.
Also I thought we agreed that for the time beeing I do the merges to make sure things are as intended?
63 commits.... 63! I even bothered to write a checklist of things to do...
This is really messing with our git history ... please revert/rebase and fix this branch before thinking about merging this atrocity.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request merged**
